### ISSUE TITLE
plugin repo down

### ISSUE THREAD

**Issue by treaz** [parzonka/Clean-Code-Method-Sorter#1]
Hi, the eclipse plugin repo is down. If you could just tell me how to use the github proj to install in eclipse that could also work :)

**Comment by parzonka** [comment]
Hi, I wasn't aware that it is down. I will look into it in the next hours. Thanks for noticing.

**Comment by treaz** [comment]
I'm really eager to test the plugin :)

**Comment by parzonka** [comment]
Okay, now I could look into it from a non-mobile device with an Eclipse installation. The update-site is not down, there is just no content served which your browser could understand. To install the plugin, you select "install new software" in Eclipse, and then paste in the url of the update-site into the field "work with: type or select a site". Install the uncategorized feature, following the installation instructions. The option "sort methods" with a keybinding should appear in the main source menu.

Hope the plugin meets your expectations, feel free to ask any further questions anytime.
